# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('short', '0003_auto_20170312_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('shortURL', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='short.NewURL')),
            ],
        ),
    ]
