# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newurl',
            name='newurl',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
