# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 07:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_auto_20170311_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newurl',
            name='url',
            field=models.CharField(max_length=200, validators=[django.core.validators.URLValidator]),
        ),
    ]
